name: Deploy static content to Pages

on:
  # Начинать деплой при пуше в ветки main или master
  push:
    branches:
      - main
      - master
  # Позволяет запустить экшен вручную из интерфейса Actions
  workflow_dispatch:

# Настройка доступов для деплоя на GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Отмена предыдущих сборок, если запущена новая
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Путь, куда собирается Vite проект
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
